on:
  merge:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: publishing to Pypi
    steps:
      - name: Update setuptools and wheel
        shell: bash
        run: 'python3 -m pip install --user --upgrade setuptools wheel'
      - name: Build bdist_wheel
        shell: bash
        run: 'python3 -m  setup.py sdist bdist_wheel'
      - name: install/upgrade twine
        shell: bash
        run: 'python3 -m pip install --user --upgrade twine'
      - name: run twine
        shell: bash
        run: 'python3 -m twine upload dist/*'
      - name: input username
        shell: bash
        run: secrets.PYPI_USERNAME
      - name: input password
        shell: bash
        run: secrets.PYPI_PASSWORD
