on:
  push:
    branches:
      - testing

jobs:
  publish:
    name: publishing to Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Current python version
        run: python3 --version || echo python3 not installed
      - name: Install Python 3.7
        run: sudo apt-get install -y --no-install-recommends python3.7 python3-pip && sudo ln -sfn /usr/bin/python3.7 /usr/bin/python3
        id: install_python_3_7
      - name: Updated python version
        run: python3 --version
      - name: Update pip
        run: python3 -m pip install --upgrade --no-cache-dir pip
        id: pip-install
      - name: Fetch/update setuptools
        run: python3 -m pip install --upgrade --no-cache-dir setuptools
        id: setuptools-install
      - name: Install python-apt
        run: sudo apt-get install -y python-apt
      - name: HACK to fix apt-get update problem w/ different python versions
        run: 'cd /usr/lib/python3/dist-packages && sudo cp apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so'
      - name: Update apt-get
        run: sudo apt-get update
      - name: Fetch/update pylint
        run: python3 -m pip install --upgrade --no-cache-dir pylint
        id: pylint-install
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Finding files
        run: find . -type f -name "*.py" > action_pylint_files.txt
        id: find-python-files
      - name: Install system requirements
        shell: bash
        run: 'sudo apt-get install -y python3-gdal gdal-bin libgdal-dev gcc g++ python3.7-dev'
        id: install-gdal-other-reqs
      - name: Install Python numpy
        shell: bash
        run: 'python3 -m pip install --upgrade --no-cache-dir numpy wheel '
        id: install-python-numpy
      - name: Install Python pygdal
        shell: bash
        run: 'sudo python3 -m pip install --no-cache-dir pygdal==2.2.3.5'
        id: install-python-pygdal
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install setup.py
        run: python3 setup.py install




#      - name: Install pep517
#        run: python3 -m pip install pep517 --user
#      - name: Build a binary wheel and a source tarball
#        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://pypi.org/project/agp/
