on:
  push:
    branches:
      - testing
jobs:
  publish:
    runs-on: ubuntu-latest
    name: publishing to Pypi
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Update setuptools and wheel
        shell: bash
        run: 'python3 -m pip install --upgrade setuptools wheel'
      - name: Build bdist_wheel
        shell: bash
        run: 'python3 setup.py sdist bdist_wheel --universal'
      - name: install/upgrade twine
        shell: bash
        run: 'python3 -m pip install --upgrade twine'
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          repository_url: https://upload.pypi.org/legacy/